package Negocio;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class InterfazAnalisis extends javax.swing.JFrame {

    /**
     * Creates new form InterfazAnalisis
     */
    Principal principal;
    String relacionExiste = "<html>";
    String relacionPosible = "<html>";
    ArrayList<String> relationships = new ArrayList<>();
    ArrayList<String> anomalias = new ArrayList<>();
    Map<String, List<String>> posibles = new HashMap<>();
    Map<String, List<String>> trigers = new HashMap<>();
    String triggers = "<html>";
    String tigre = "";
    String anomalia="<html>";
    public InterfazAnalisis() {
        initComponents();
        principal = new Principal();
        this.setLocationRelativeTo(null);
        this.jTPPosibleRelacion.disable();
        this.jTPRelacionExistente.disable();
        jTPPosibleRelacion.setDisabledTextColor(Color.BLACK);
        jTPRelacionExistente.setDisabledTextColor(Color.BLACK);
        jTPPosibleRelacion.setContentType("text/html");
        jTPRelacionExistente.setContentType("text/html");
        this.jTPTrigger.disable();
        this.jTPAnomalia.disable();
        jTPAnomalia.setDisabledTextColor(Color.BLACK);
        jTPTrigger.setDisabledTextColor(Color.BLACK);
        jTPAnomalia.setContentType("text/html");
        jTPTrigger.setContentType("text/html");
        this.jTFBD.setText("");
        jBLogs.setEnabled(false);
    }
    
    public String leerMap(Map<String, List<String>> lectura){
        String cadena = "";
        for (Map.Entry<String, List<String>> entry : lectura.entrySet()) {
            cadena += "<hr><b>"+ entry.getKey() + "</b> -> " + entry.getValue();
        }
        return cadena;
    }
    
    public String txtPlain(Map<String, List<String>> lectura){
        String cadena = "";
        for (Map.Entry<String, List<String>> entry : lectura.entrySet()) {
            cadena += "\r\n"+ entry.getKey() + " -> " + entry.getValue();
        }
        return cadena;
    }
    
    public String txtPlainArray(ArrayList<String> lectura){
        String cadena = "";
        for(String hoja:lectura){
            cadena += "\r\n"+ hoja;
        }
        return cadena;
    }
    
    public String leerArray(ArrayList<String> lectura){
        String cadena = "";
        for(String hoja:lectura){
            cadena += "<hr>" + hoja;
        }
        
        return cadena;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPPosibleRelacion = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTPAnomalia = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jTFBD = new javax.swing.JTextField();
        jBuscarBD = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBLogs = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTPRelacionExistente = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTPTrigger = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Análisis de Anomalías");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Auditoría Informática");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Buscar base de datos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Posibles relaciones");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Anomalìas de datos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        jScrollPane1.setViewportView(jTPPosibleRelacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 370, 210));

        jScrollPane2.setViewportView(jTPAnomalia);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 370, 210));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Grupo 4");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jTFBD.setText("jTextField1");
        getContentPane().add(jTFBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 350, -1));

        jBuscarBD.setText("Buscar BD");
        jBuscarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarBDActionPerformed(evt);
            }
        });
        getContentPane().add(jBuscarBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Relaciones existentes");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Triggers");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jBLogs.setText("Generar Logs");
        jBLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLogsActionPerformed(evt);
            }
        });
        getContentPane().add(jBLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, -1));

        jScrollPane3.setViewportView(jTPRelacionExistente);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 350, 210));

        jScrollPane4.setViewportView(jTPTrigger);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 350, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBuscarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarBDActionPerformed
        this.jBLogs.setEnabled(true);
        if(this.jTFBD.getText().equals(null) || this.jTFBD.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese el nombre de la base de datos");
        }else{
            try {
                principal.obtenerTablas(this.jTFBD.getText());
                relationships = principal.buscarRelaciones(this.jTFBD.getText());
                relacionExiste += leerArray(relationships) + "</html>";
                posibles = principal.posiblesRelaciones(this.jTFBD.getText());
                relacionPosible += "<hr> <b>Tabla Principal: [Tabla Relacionada - atributo]</b>";
                relacionPosible += leerMap(posibles) + "</html>";
                this.jTPRelacionExistente.setText(relacionExiste);
                this.jTPPosibleRelacion.setText(relacionPosible);
          
       //        tigre += principal.CrearTablaAuditoria(this.jTFBD.getText());
         //      tigre += principal.CrearDisparadores(this.jTFBD.getText());
                trigers = principal.obtenerTrigger(this.jTFBD.getText());
                triggers += leerMap(trigers) + "</html>";
                this.jTPTrigger.setText(triggers);
                anomalias = principal.getAnormalies(this.jTFBD.getText());
                anomalia += leerArray(anomalias) + "</html>";
                this.jTPAnomalia.setText(anomalia);
                
                
            } catch (SQLException ex) {
                Logger.getLogger(InterfazAnalisis.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBuscarBDActionPerformed

    private void jBLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLogsActionPerformed
        String txtplano = "";
        txtplano = "Relaciones existentes \r\n" + txtPlainArray(relationships) +"\r\n";
        principal.CrearLog("RelacionesExistentes",txtplano,this.jTFBD.getText());
        txtplano = "\r\n\r\nRelaciones posibles \r\n" + txtPlain(posibles)+"\r\n";
        principal.CrearLog("RelacionesPosibles",txtplano,this.jTFBD.getText());
        txtplano = "\r\n\r\nTriggers \r\n" + txtPlain(trigers)+"\r\n";
        principal.CrearLog("Trigger",txtplano,this.jTFBD.getText());
        txtplano = "\r\n\r\nSCRIPT TRIGGERS \r\n" + tigre+"\r\n";
        principal.CrearLog("TriggerScript",txtplano,this.jTFBD.getText());
        txtplano = "\r\n\r\nANOMALIAS DE DATOS \r\n" + txtPlainArray(anomalias)+"\r\n";
        principal.CrearLog("Anomalias_Datos",txtplano,this.jTFBD.getText());
    }//GEN-LAST:event_jBLogsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAnalisis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLogs;
    private javax.swing.JButton jBuscarBD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTFBD;
    private javax.swing.JTextPane jTPAnomalia;
    private javax.swing.JTextPane jTPPosibleRelacion;
    private javax.swing.JTextPane jTPRelacionExistente;
    private javax.swing.JTextPane jTPTrigger;
    // End of variables declaration//GEN-END:variables
}
